from __future__ import annotations

from typing import Any

from core.gencode.runtime_skill_wrapper import check_answer, generate_for_skill

SKILL_ID = 'vh_數學B1_PointSlopeForm'
GENERATOR_KEYS = ['vh_數學B1_PointSlopeForm:equation_write_line_equation_from_point_slope_short_answer:draft_v1', 'vh_數學B1_PointSlopeForm:equation_write_line_equation_from_two_points_short_answer:draft_v1', 'vh_數學B1_PointSlopeForm:equation_write_perpendicular_bisector_from_two_points_short_answer:draft_v1', 'vh_數學B1_PointSlopeForm:equation_write_line_equation_from_slope_and_intercept_short_answer:draft_v1', 'vh_數學B1_PointSlopeForm:equation_write_triangle_median_line_from_vertices_short_answer:draft_v1']
GENERATOR_SPECS = [{'problem_type_id': 'equation_write_line_equation_from_point_slope_short_answer', 'checker_key': 'linear_equation_equivalent_checker', 'equivalence_type': 'linear_equation_equivalent', 'generator_readiness': 'runtime_ready', 'answer_type': 'equation', 'template_slot': 'line_equation_from_point_slope', 'base_problem_type_id': 'equation_write_line_equation_from_point_slope_short_answer', 'target_task': 'write_line_equation_from_point_slope', 'presentation_mode': 'short_answer', 'answer_shape': 'linear_equation'}, {'problem_type_id': 'equation_write_line_equation_from_two_points_short_answer', 'checker_key': 'linear_equation_equivalent_checker', 'equivalence_type': 'linear_equation_equivalent', 'generator_readiness': 'runtime_ready', 'answer_type': 'equation', 'template_slot': 'line_equation_from_two_points', 'base_problem_type_id': 'equation_write_line_equation_from_two_points_short_answer', 'target_task': 'write_line_equation_from_two_points', 'presentation_mode': 'short_answer', 'answer_shape': 'linear_equation'}, {'problem_type_id': 'equation_write_perpendicular_bisector_from_two_points_short_answer', 'checker_key': 'linear_equation_equivalent_checker', 'equivalence_type': 'linear_equation_equivalent', 'generator_readiness': 'runtime_ready', 'answer_type': 'equation', 'template_slot': 'perpendicular_bisector_from_two_points', 'base_problem_type_id': 'equation_write_perpendicular_bisector_from_two_points_short_answer', 'target_task': 'write_perpendicular_bisector_from_two_points', 'presentation_mode': 'short_answer', 'answer_shape': 'linear_equation'}, {'problem_type_id': 'equation_write_line_equation_from_slope_and_intercept_short_answer', 'checker_key': 'linear_equation_equivalent_checker', 'equivalence_type': 'linear_equation_equivalent', 'generator_readiness': 'runtime_ready', 'answer_type': 'equation', 'template_slot': 'line_equation_from_slope_and_intercept', 'base_problem_type_id': 'equation_write_line_equation_from_slope_and_intercept_short_answer', 'target_task': 'write_line_equation_from_slope_and_intercept', 'presentation_mode': 'short_answer', 'answer_shape': 'linear_equation'}, {'problem_type_id': 'equation_write_triangle_median_line_from_vertices_short_answer', 'checker_key': 'linear_equation_equivalent_checker', 'equivalence_type': 'linear_equation_equivalent', 'generator_readiness': 'runtime_ready', 'answer_type': 'equation', 'template_slot': 'triangle_median_line_from_vertices', 'base_problem_type_id': 'equation_write_triangle_median_line_from_vertices_short_answer', 'target_task': 'write_triangle_median_line_from_vertices', 'presentation_mode': 'short_answer', 'answer_shape': 'linear_equation'}]

def generate(level: int = 1, seed: int | None = None, difficulty: int | str | None = None, **kwargs) -> dict[str, Any]:
    return generate_for_skill(SKILL_ID, GENERATOR_SPECS, level=level, seed=seed, difficulty=difficulty)

def check(user_answer: Any, correct_answer: Any, question_payload: dict[str, Any] | None = None):
    return check_answer(user_answer, correct_answer, payload=question_payload)
