# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any


SUBSKILL_LABEL_MAP: dict[str, str] = {
    # integer
    "sign_handling": "正負號判讀",
    "add_sub": "加減運算",
    "mul_div": "乘除運算",
    "order_of_operations": "運算順序",
    "bracket_scope": "括號範圍判斷",
    "absolute_value": "絕對值概念",
    "exact_divisibility": "整除判斷",
    "isomorphic_structure": "結構辨識",
    # fraction
    "proper_improper_fraction": "真分數與假分數轉換",
    "mixed_numbers": "帶分數處理",
    "sign_normalization": "分數正負號統一",
    "decimal_to_fraction_exact_conversion": "小數轉分數",
    "simplest_form_reduction": "約成最簡分數",
    "equivalent_fraction_scaling": "等值分數同比縮放",
    "reciprocal_transform": "倒數轉換",
    "preserve_value_invariance": "分數值不變",
    "positive_fraction_comparison": "正分數比較",
    "negative_fraction_comparison": "負分數比較",
    "mixed_number_comparison": "帶分數比較",
    "multiply": "乘法運算",
    "divide": "除法運算",
    "nested_parentheses": "巢狀括號處理",
    "decimal_fraction_mixed_arithmetic": "分數小數混合運算",
    "telescoping_products": "連乘約分",
    "remaining_amount": "剩餘量理解",
    "container_weight": "容器重量題意轉換",
    "before_after_ratio": "前後比例比較",
    "share_comparison": "分配比較",
    # polynomial
    "normalize_terms": "整理項次與標準形式",
    "combine_like_terms": "合併同類項",
    "sign_distribution": "符號分配",
    "unknown_target_preservation": "保留未知量結構",
    "expand_monomial": "單項式分配展開",
    "expand_binomial": "雙項式展開",
    "special_identity": "乘法公式",
    "long_division": "長除法步驟",
    "quotient_remainder_format": "商與餘式表示",
    "reverse_division_reconstruction": "反推被除式",
    "geometry_formula": "幾何公式列式",
    "composite_region_modeling": "複合圖形建模",
    "family_isomorphism": "同型結構辨識",
    # radicals
    "simplify": "根式化簡",
    "multiply_terms": "根式乘法",
    "divide_terms": "根式除法",
    "distribute": "分配律",
    "binomial_expand": "雙括號展開",
    "conjugate_rationalize": "共軛有理化",
    "fractional_radical": "分式根式處理",
    "mixed_number_radical": "帶分數根式",
    "structure_isomorphism": "結構辨識",
    # power bridge subskills in use
    "power_notation_basics": "乘方記號基礎",
    "signed_power_interpretation": "正負底數乘方判讀",
    "parenthesized_negative_base": "負底數括號判讀",
    "minus_outside_power": "外部負號與乘方先後",
    "power_precedence_in_mixed_ops": "乘方在混合運算中的優先序",
    "signed_power_evaluation": "含符號乘方值計算",
    "mixed_power_arithmetic": "乘方混合四則運算",
    "same_base_multiplication_rule": "同底數乘法規則",
    "power_building_from_repetition": "重複乘法建構乘方",
    "power_of_power_rule": "冪的冪規則",
    "product_power_distribution": "積的冪分配規則",
    "fraction_power_distribution": "分式乘方分配規則",
}


SKILL_DIAGNOSTIC_CATALOG: dict[str, dict[str, dict[str, Any]]] = {
    "integer": {
        "I1": {
            "label_zh": "數線型整數加減",
            "description_zh": "在數線概念下進行整數加減，理解往右加、往左減與正負方向。",
            "common_error_zh": "容易把正負方向看反，或在加負數、減負數時符號判斷錯誤。",
            "prerequisite_ids": [],
            "subskills": ["sign_handling", "add_sub"],
        },
        "I2": {
            "label_zh": "平面整數加減",
            "description_zh": "直接對整數做加減運算，不依賴數線圖像。",
            "common_error_zh": "容易在正負整數混合加減時出現符號錯誤。",
            "prerequisite_ids": ["I1"],
            "subskills": ["sign_handling", "add_sub"],
        },
        "I3": {
            "label_zh": "平面整數乘除",
            "description_zh": "進行整數的乘法與除法，並判斷正負號與整除性。",
            "common_error_zh": "常在正負號規則或整除判斷上出錯。",
            "prerequisite_ids": ["I2"],
            "subskills": ["sign_handling", "mul_div", "exact_divisibility"],
        },
        "I4": {
            "label_zh": "整數四則混合",
            "description_zh": "同時處理整數的加、減、乘、除，並遵守運算順序。",
            "common_error_zh": "常忽略先乘除後加減，或在中間步驟符號處理失誤。",
            "prerequisite_ids": ["I2", "I3"],
            "subskills": ["sign_handling", "add_sub", "mul_div", "order_of_operations"],
        },
        "I5": {
            "label_zh": "括號整數四則",
            "description_zh": "處理含括號的整數四則運算，理解括號優先與括號前符號影響。",
            "common_error_zh": "去括號時容易漏改符號，或沒有先算括號內。",
            "prerequisite_ids": ["I4"],
            "subskills": ["sign_handling", "bracket_scope", "order_of_operations"],
        },
        "I6": {
            "label_zh": "絕對值整數四則",
            "description_zh": "在絕對值情境下進行整數運算，理解絕對值表示距離。",
            "common_error_zh": "常把絕對值直接當符號，或忽略先算絕對值內部。",
            "prerequisite_ids": ["I2"],
            "subskills": ["sign_handling", "absolute_value"],
        },
        "I7": {
            "label_zh": "巢狀整除結構",
            "description_zh": "處理含括號、絕對值與多層結構的整除型題目。",
            "common_error_zh": "容易在多層結構中遺漏整除限制，或括號/絕對值處理順序錯誤。",
            "prerequisite_ids": ["I3", "I5", "I6"],
            "subskills": ["sign_handling", "mul_div", "bracket_scope", "absolute_value", "exact_divisibility"],
        },
        "I8": {
            "label_zh": "綜合結構題",
            "description_zh": "整合整數四則、括號、絕對值與整除規則的綜合題。",
            "common_error_zh": "常在多個規則同時出現時失去步驟控制，導致整體結構判斷錯誤。",
            "prerequisite_ids": ["I4", "I5", "I6", "I7"],
            "subskills": ["sign_handling", "add_sub", "mul_div", "order_of_operations", "bracket_scope", "absolute_value", "exact_divisibility", "isomorphic_structure"],
        },
        "I9": {
            "label_zh": "乘方符號與括號判讀",
            "description_zh": "分辨負號在括號內外時的乘方意義，理解 (-a)^n 與 -a^n 差異。",
            "common_error_zh": "常把外部負號當作底數一部分，導致整題符號錯誤。",
            "prerequisite_ids": ["I4", "I5"],
            "subskills": ["power_notation_basics", "signed_power_interpretation", "parenthesized_negative_base", "minus_outside_power"],
        },
        "I10": {
            "label_zh": "整數乘方混合運算",
            "description_zh": "處理含乘方、乘除與加減的整數綜合算式，遵守優先序。",
            "common_error_zh": "常忽略乘方優先，或在負號與乘方結合時判斷錯誤。",
            "prerequisite_ids": ["I4", "I9"],
            "subskills": ["power_precedence_in_mixed_ops", "signed_power_evaluation", "mixed_power_arithmetic"],
        },
    },
    "fraction": {
        "F1": {
            "label_zh": "分數化簡",
            "description_zh": "把分數約成最簡形式，並處理帶分數、假分數與正負號。",
            "common_error_zh": "常忘記約分到底，或正負號位置不一致。",
            "prerequisite_ids": [],
            "subskills": ["proper_improper_fraction", "mixed_numbers", "sign_normalization", "simplest_form_reduction"],
        },
        "F2": {
            "label_zh": "等值分數填空",
            "description_zh": "理解分數值不變，能找出等值分數中的缺項。",
            "common_error_zh": "常只改分子或只改分母，沒有保持等比例。",
            "prerequisite_ids": ["F1"],
            "subskills": ["equivalent_fraction_scaling", "sign_normalization"],
        },
        "F3": {
            "label_zh": "分數值不變",
            "description_zh": "理解分數在同乘同除非零數時值不變。",
            "common_error_zh": "不知道什麼操作會改變分數值，或比例縮放不一致。",
            "prerequisite_ids": ["F1", "F2"],
            "subskills": ["preserve_value_invariance", "equivalent_fraction_scaling"],
        },
        "F4": {
            "label_zh": "分數比較",
            "description_zh": "比較正分數、負分數與帶分數的大小。",
            "common_error_zh": "常直接比較分子分母大小，忽略通分或負數大小规律。",
            "prerequisite_ids": ["F1", "F2"],
            "subskills": ["positive_fraction_comparison", "negative_fraction_comparison", "mixed_number_comparison"],
        },
        "F5": {
            "label_zh": "分數加減",
            "description_zh": "進行分數的加減運算，必要時先通分或轉換帶分數。",
            "common_error_zh": "常直接分子分母相加減，或忘記先通分。",
            "prerequisite_ids": ["F1", "F2", "F4"],
            "subskills": ["add_sub", "nested_parentheses", "mixed_numbers"],
        },
        "F6": {
            "label_zh": "分數乘法",
            "description_zh": "進行分數乘法，並視情況約分或處理帶分數。",
            "common_error_zh": "常忘記先約分、帶分數未先化假分數，或步驟過度混亂。",
            "prerequisite_ids": ["F1"],
            "subskills": ["multiply", "mixed_numbers", "telescoping_products"],
        },
        "F7": {
            "label_zh": "分數除法",
            "description_zh": "進行分數除法，理解除以分數等於乘以其倒數。",
            "common_error_zh": "常忘記倒數轉換，或分子分母翻轉錯誤。",
            "prerequisite_ids": ["F6", "F8"],
            "subskills": ["divide", "mixed_numbers", "decimal_fraction_mixed_arithmetic"],
        },
        "F8": {
            "label_zh": "倒數",
            "description_zh": "理解倒數的意義，並正確求出一個數的倒數。",
            "common_error_zh": "常把負號、整數或帶分數的倒數寫錯。",
            "prerequisite_ids": ["F1"],
            "subskills": ["reciprocal_transform"],
        },
        "F9": {
            "label_zh": "分數小數混合四則",
            "description_zh": "處理分數與小數混合的四則運算，必要時做格式轉換。",
            "common_error_zh": "常在小數轉分數、分數轉小數時出錯，或混合運算順序錯亂。",
            "prerequisite_ids": ["F5", "F6", "F7"],
            "subskills": ["decimal_to_fraction_exact_conversion", "add_sub", "multiply", "divide", "nested_parentheses"],
        },
        "F10": {
            "label_zh": "分數應用題",
            "description_zh": "把生活情境轉成分數運算，例如剩餘量、重量、比例與分配比較。",
            "common_error_zh": "常看不懂題意中的『剩下、前後、分配』對應哪種分數關係。",
            "prerequisite_ids": ["F5", "F6", "F7", "F9"],
            "subskills": ["remaining_amount", "container_weight", "before_after_ratio", "share_comparison"],
        },
        "F11": {
            "label_zh": "同底數冪相乘",
            "description_zh": "理解同底數相乘時，指數可以相加。",
            "common_error_zh": "常把底數也相加，或把指數相乘。",
            "prerequisite_ids": ["F6"],
            "subskills": ["same_base_multiplication_rule", "power_building_from_repetition"],
        },
        "F12": {
            "label_zh": "冪的冪",
            "description_zh": "理解 (a^m)^n 的指數規則。",
            "common_error_zh": "常把指數相加而不是相乘。",
            "prerequisite_ids": ["F11"],
            "subskills": ["power_of_power_rule"],
        },
        "F13": {
            "label_zh": "積的冪分配",
            "description_zh": "理解 (ab)^n 可分配到每個因數。",
            "common_error_zh": "常只對其中一個因數乘方，或忽略兩邊指數一致。",
            "prerequisite_ids": ["F11", "F12"],
            "subskills": ["product_power_distribution", "fraction_power_distribution"],
        },
    },
    "polynomial": {
        "F1": {
            "label_zh": "平面多項式加減",
            "description_zh": "整理多項式中的項，並正確合併同類項。",
            "common_error_zh": "常把不同次方的項誤合併，或整理順序混亂。",
            "prerequisite_ids": [],
            "subskills": ["normalize_terms", "combine_like_terms"],
        },
        "F2": {
            "label_zh": "巢狀多項式加減",
            "description_zh": "處理帶括號或巢狀結構的多項式加減。",
            "common_error_zh": "常在去括號時漏改符號，導致整串式子錯誤。",
            "prerequisite_ids": ["F1"],
            "subskills": ["sign_distribution", "combine_like_terms", "family_isomorphism"],
        },
        "F3": {
            "label_zh": "未知多項式求解",
            "description_zh": "利用已知條件反推出未知多項式或缺項。",
            "common_error_zh": "常在移項、對應係數或保留未知量時出錯。",
            "prerequisite_ids": ["F1", "F2"],
            "subskills": ["sign_distribution", "unknown_target_preservation"],
        },
        "F4": {
            "label_zh": "單項式乘法",
            "description_zh": "用單項式去乘多項式，理解分配律。",
            "common_error_zh": "常漏乘某一項，或係數、指數處理不完整。",
            "prerequisite_ids": ["F1"],
            "subskills": ["expand_monomial"],
        },
        "F5": {
            "label_zh": "多項式乘法展開",
            "description_zh": "展開兩個多項式相乘的結果，並合併同類項。",
            "common_error_zh": "常漏乘交叉項，或展開後沒有正確整理。",
            "prerequisite_ids": ["F1", "F4"],
            "subskills": ["expand_binomial", "combine_like_terms"],
        },
        "F6": {
            "label_zh": "乘法公式",
            "description_zh": "應用平方差、完全平方等乘法公式快速化簡。",
            "common_error_zh": "常把公式套錯，或符號、係數位置搞混。",
            "prerequisite_ids": ["F5"],
            "subskills": ["special_identity"],
        },
        "F7": {
            "label_zh": "單項式除法直接化簡",
            "description_zh": "用單項式除多項式後，直接寫成化簡結果。",
            "common_error_zh": "常在每一項分別相除時漏項，或係數、次方約掉錯誤。",
            "prerequisite_ids": ["F1", "F4"],
            "subskills": ["normalize_terms"],
        },
        "F8": {
            "label_zh": "單項式除法（商與餘式）",
            "description_zh": "用單項式去除多項式，並以商與餘式的形式表示答案。",
            "common_error_zh": "常把答案寫成分式而不是商餘式，或在除法分配與符號處理上出錯。",
            "prerequisite_ids": ["F1", "F7"],
            "subskills": ["long_division", "quotient_remainder_format"],
        },
        "F9": {
            "label_zh": "多項式長除法",
            "description_zh": "使用長除法處理多項式除法，並寫出商與餘式。",
            "common_error_zh": "常不熟長除法步驟、對位錯誤，或最後餘式表示不完整。",
            "prerequisite_ids": ["F5", "F8"],
            "subskills": ["long_division", "quotient_remainder_format"],
        },
        "F10": {
            "label_zh": "反推除法",
            "description_zh": "根據商、除式與餘式反推出原來的被除式。",
            "common_error_zh": "常忘記『被除式 = 除式 × 商 + 餘式』的結構。",
            "prerequisite_ids": ["F8", "F9"],
            "subskills": ["reverse_division_reconstruction"],
        },
        "F11": {
            "label_zh": "綜合化簡",
            "description_zh": "綜合使用展開、乘法公式、同類項合併等規則進行化簡。",
            "common_error_zh": "常在多個規則同時出現時步驟混亂，尤其容易漏掉乘方、展開或符號變化。",
            "prerequisite_ids": ["F1", "F5", "F6"],
            "subskills": ["expand_binomial", "special_identity", "combine_like_terms", "family_isomorphism"],
        },
        "F12": {
            "label_zh": "幾何公式應用",
            "description_zh": "把多項式運算套到面積、周長等幾何公式中。",
            "common_error_zh": "常把圖形關係與代數式對應錯誤。",
            "prerequisite_ids": ["F1", "F5"],
            "subskills": ["geometry_formula"],
        },
        "F13": {
            "label_zh": "複合圖形應用",
            "description_zh": "利用多項式描述複合圖形的面積或幾何關係。",
            "common_error_zh": "常在拆圖、列式與合併幾何量時出錯。",
            "prerequisite_ids": ["F12"],
            "subskills": ["geometry_formula", "composite_region_modeling"],
        },
    },
    "radical": {
        "p0": {"label_zh": "單根式化簡", "description_zh": "把根號內的數拆解並化成最簡根式。", "common_error_zh": "常無法找出可開根的因數，或把根號拆錯。", "prerequisite_ids": [], "subskills": ["simplify"]},
        "p1": {"label_zh": "純根式加減", "description_zh": "對同類根式進行加減。", "common_error_zh": "常把不同根號內容的式子硬加在一起。", "prerequisite_ids": ["p0"], "subskills": ["combine_like_terms"]},
        "p1b": {"label_zh": "括號根式加減", "description_zh": "處理含括號的根式加減，注意括號影響。", "common_error_zh": "常在去括號時漏改符號，或沒有先整理同類根式。", "prerequisite_ids": ["p1"], "subskills": ["combine_like_terms", "bracket_scope"]},
        "p1c": {"label_zh": "分數根式加減", "description_zh": "處理係數是分數的根式加減。", "common_error_zh": "常同時在分數與根式兩邊出錯，導致整理失敗。", "prerequisite_ids": ["p1"], "subskills": ["combine_like_terms", "fractional_radical"]},
        "p2a": {"label_zh": "根式直接相乘", "description_zh": "直接計算根式與根式的乘法。", "common_error_zh": "常把係數與根號內數字的乘法順序弄混。", "prerequisite_ids": ["p0"], "subskills": ["multiply_terms"]},
        "p2b": {"label_zh": "根式分配律乘法", "description_zh": "利用分配律進行根式乘法。", "common_error_zh": "常漏乘某一項，或分配後沒有再化簡。", "prerequisite_ids": ["p2a"], "subskills": ["multiply_terms", "distribute"]},
        "p2c": {"label_zh": "根式雙括號展開", "description_zh": "展開兩個括號中的根式乘法。", "common_error_zh": "常漏掉中間交叉項，或展開後整理不完全。", "prerequisite_ids": ["p2b"], "subskills": ["multiply_terms", "distribute", "binomial_expand"]},
        "p2d": {"label_zh": "根式完全平方", "description_zh": "辨識並使用根式的完全平方結構。", "common_error_zh": "常誤判平方公式，或中間項係數寫錯。", "prerequisite_ids": ["p2c"], "subskills": ["multiply_terms", "binomial_expand"]},
        "p2e": {"label_zh": "根式平方差", "description_zh": "應用平方差公式處理根式乘法。", "common_error_zh": "常把平方差與完全平方搞混。", "prerequisite_ids": ["p2c"], "subskills": ["multiply_terms", "binomial_expand"]},
        "p2f": {"label_zh": "整數乘根式", "description_zh": "處理整數與根式相乘。", "common_error_zh": "常不知道整數要乘在根式外，或化簡位置錯誤。", "prerequisite_ids": ["p0"], "subskills": ["multiply_terms"]},
        "p2g": {"label_zh": "根式乘分數", "description_zh": "處理根式與分數相乘。", "common_error_zh": "常在分數係數與根式化簡上同時失誤。", "prerequisite_ids": ["p2a"], "subskills": ["multiply_terms", "fractional_radical"]},
        "p2h": {"label_zh": "分數乘根式", "description_zh": "處理分數係數乘上根式。", "common_error_zh": "常將分數與根號內部錯誤混合處理。", "prerequisite_ids": ["p2a"], "subskills": ["multiply_terms", "fractional_radical"]},
        "p3a": {"label_zh": "表達式除以根式", "description_zh": "把整個代數式除以根式並整理。", "common_error_zh": "常忘記整個分子都要一起除，或括號範圍判斷錯誤。", "prerequisite_ids": ["p1", "p2a"], "subskills": ["divide_terms", "bracket_scope"]},
        "p3b": {"label_zh": "a/√b 有理化", "description_zh": "將分母中的根式消去，完成有理化。", "common_error_zh": "常不熟有理化目的，或分子分母沒有同乘適當根式。", "prerequisite_ids": ["p2a"], "subskills": ["divide_terms", "conjugate_rationalize"]},
        "p3c": {"label_zh": "根式直接相除", "description_zh": "直接計算根式除法並化簡。", "common_error_zh": "常把分子分母根號拆錯，或最後沒有再化簡。", "prerequisite_ids": ["p2a"], "subskills": ["divide_terms"]},
        "p4": {"label_zh": "分式根式乘法", "description_zh": "處理同時包含分式與根式的乘法。", "common_error_zh": "常在分式結構與根式結構之間來回出錯。", "prerequisite_ids": ["p2g", "p2h"], "subskills": ["fractional_radical", "structure_isomorphism"]},
        "p4b": {"label_zh": "根式分式相除", "description_zh": "處理根式分式的除法與有理化。", "common_error_zh": "常在除法轉乘法與有理化的兩步之間斷掉。", "prerequisite_ids": ["p3b", "p4"], "subskills": ["divide_terms", "conjugate_rationalize"]},
        "p4c": {"label_zh": "根號內分數連算", "description_zh": "處理根號內還有分數或連續分式的計算。", "common_error_zh": "常無法正確拆解層次，導致根號內外混算。", "prerequisite_ids": ["p1c", "p4"], "subskills": ["fractional_radical", "structure_isomorphism"]},
        "p4d": {"label_zh": "混合根式分式除法", "description_zh": "綜合處理根式、分式與除法的題型。", "common_error_zh": "常在多個規則同時出現時步驟失控。", "prerequisite_ids": ["p4b", "p4c"], "subskills": ["divide_terms", "conjugate_rationalize", "fractional_radical"]},
        "p5a": {"label_zh": "整數分子共軛有理化", "description_zh": "利用共軛式對整數分子的分式做有理化。", "common_error_zh": "常不熟共軛配對，或乘完後公式整理錯誤。", "prerequisite_ids": ["p3b"], "subskills": ["divide_terms", "conjugate_rationalize"]},
        "p5b": {"label_zh": "根式分子共軛有理化", "description_zh": "利用共軛式處理分子含根式的有理化問題。", "common_error_zh": "常把共軛式寫錯，或不知道分子分母都要同乘。", "prerequisite_ids": ["p5a"], "subskills": ["divide_terms", "conjugate_rationalize"]},
        "p6": {"label_zh": "多步驟綜合題", "description_zh": "綜合使用化簡、加減、乘除與結構辨識處理根式。", "common_error_zh": "常在多個步驟串連時失去節奏，不知道先做哪一步。", "prerequisite_ids": ["p1", "p2", "p3"], "subskills": ["simplify", "combine_like_terms", "multiply_terms", "divide_terms", "structure_isomorphism"]},
        "p7": {"label_zh": "帶分數根式加減", "description_zh": "處理帶分數形式的根式加減。", "common_error_zh": "常在帶分數轉換與同類根式整理上一起出錯。", "prerequisite_ids": ["p1", "p1c"], "subskills": ["mixed_number_radical", "combine_like_terms"]},
    },
}


def get_family_diagnostic_info(skill_type: str, family_id: str) -> dict[str, Any]:
    st = str(skill_type or "generic").strip().lower() or "generic"
    fid = str(family_id or "").strip()
    section = SKILL_DIAGNOSTIC_CATALOG.get(st, {})
    raw = dict(section.get(fid, {}))
    label_zh = str(raw.get("label_zh") or fid or "未命名技能")
    description_zh = str(raw.get("description_zh") or "此題型目前使用通用診斷規則。")
    common_error_zh = str(raw.get("common_error_zh") or "常見錯誤多與符號、順序或表示方式有關。")
    prerequisite_ids = [str(x).strip() for x in (raw.get("prerequisite_ids") or []) if str(x).strip()]
    prerequisite_labels_zh: list[str] = []
    for pid in prerequisite_ids:
        pnode = section.get(pid, {})
        prerequisite_labels_zh.append(str(pnode.get("label_zh") or pid))
    subskills = [str(x).strip() for x in (raw.get("subskills") or []) if str(x).strip()]
    subskills_zh = [SUBSKILL_LABEL_MAP.get(s, s) for s in subskills]
    return {
        "family_id": fid,
        "label_zh": label_zh,
        "description_zh": description_zh,
        "common_error_zh": common_error_zh,
        "prerequisite_ids": prerequisite_ids,
        "prerequisite_labels_zh": prerequisite_labels_zh,
        "subskills": subskills,
        "subskills_zh": subskills_zh,
    }
