"""Domain utilities for vocational math B4."""

from .binomial_domain_functions import (
    binomial_coefficient_sum,
    binomial_expansion_coefficients,
    binomial_term_coefficient,
    pascal_identity,
    pascal_triangle_row,
)
from .b4_validators import (
    validate_answer_in_choices,
    validate_choices_unique,
    validate_expression_answer,
    validate_integer_answer,
    validate_n_ge_r,
    validate_no_unfilled_placeholder,
    validate_nonnegative_integer,
    validate_parameter_tuple_not_seen,
    validate_polynomial_answer,
    validate_positive_integer,
    validate_problem_payload_contract,
)
from .counting_domain_functions import (
    addition_principle_count,
    adjacent_arrangement_count,
    combination,
    combination_equation_solve_n,
    digit_arrangement_count,
    divisor_count_from_prime_factorization,
    enumeration_count,
    factorial,
    factorial_ratio_solve_n,
    multiplication_principle_count,
    non_adjacent_arrangement_count,
    permutation,
    polygon_diagonal_count,
    polygon_triangle_count,
    repeated_assignment_count,
    repeated_choice_count,
    repeated_digit_arrangement_count,
)

__all__ = [
    "addition_principle_count",
    "adjacent_arrangement_count",
    "binomial_coefficient_sum",
    "binomial_expansion_coefficients",
    "binomial_term_coefficient",
    "combination",
    "combination_equation_solve_n",
    "digit_arrangement_count",
    "divisor_count_from_prime_factorization",
    "enumeration_count",
    "factorial",
    "factorial_ratio_solve_n",
    "multiplication_principle_count",
    "non_adjacent_arrangement_count",
    "pascal_identity",
    "pascal_triangle_row",
    "permutation",
    "polygon_diagonal_count",
    "polygon_triangle_count",
    "repeated_assignment_count",
    "repeated_choice_count",
    "repeated_digit_arrangement_count",
    "validate_answer_in_choices",
    "validate_choices_unique",
    "validate_expression_answer",
    "validate_integer_answer",
    "validate_n_ge_r",
    "validate_no_unfilled_placeholder",
    "validate_nonnegative_integer",
    "validate_parameter_tuple_not_seen",
    "validate_polynomial_answer",
    "validate_positive_integer",
    "validate_problem_payload_contract",
]
