# -*- coding: utf-8 -*-
"""Tests for Auto Triage to Draft and Isolated Validation Pipeline with Executable Workspace Gate."""

from __future__ import annotations

import json
import sqlite3
import pytest
from pathlib import Path

from core.gencode.services.proposal_advance_pipeline_service import (
    advance_capability_proposals,
    build_executable_domain_workspaces
)
from core.gencode.schema.gencode_component_tracker_inspection import apply_tracker_ddl

@pytest.fixture
def setup_env(tmp_path: Path) -> tuple[Path, Path, sqlite3.Connection]:
    proposal_root = tmp_path / "proposals"
    draft_root = tmp_path / "drafts"
    proposal_root.mkdir()
    draft_root.mkdir()

    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    apply_tracker_ddl(conn)
    
    # Insert tracker payloads for source components
    conn.execute(
        """
        INSERT INTO gencode_component_tracker (textbook_example_id, skill_id, component_id, gencode_status, induced_spec_payload)
        VALUES (4401, 'test_skill', 'src_4401', 'failed', '{"required_capabilities": ["cap1"], "problem_type_id": "cap1"}')
        """
    )
    conn.execute(
        """
        INSERT INTO gencode_component_tracker (textbook_example_id, skill_id, component_id, gencode_status, induced_spec_payload)
        VALUES (4426, 'test_skill', 'src_4426', 'failed', '{"required_capabilities": ["collinear_trisection_coordinate"], "problem_type_id": "collinear_trisection_coordinate"}')
        """
    )
    conn.commit()
    
    return proposal_root, draft_root, conn

def test_executable_workspace_gate_scenarios(setup_env: tuple[Path, Path, sqlite3.Connection]):
    proposal_root, draft_root, conn = setup_env

    # 1. Setup Proposal (Valid proposed proposal)
    p1 = {
        "proposal_schema": "domain_capability_proposal.v1",
        "proposal_id": "capability_prop1",
        "skill_id": "test_skill",
        "required_capabilities": ["cap1"],
        "source_example_ids": [4401],
        "best_reuse_domain": "coordinate_geometry.line_equation",
        "recommended_action": "new_generic_operation",
        "status": "proposed"
    }
    (proposal_root / "capability_prop1.json").write_text(json.dumps(p1), encoding="utf-8")

    # Helper function to get current workspace files dynamically
    def get_workspace_files():
        revs = sorted(list((draft_root / "capability_prop1").glob("revision_*")))
        if not revs:
            raise FileNotFoundError("No revision directory found yet.")
        ws_dir = revs[-1] / "workspace"
        impl_file = ws_dir / "implementation_candidate.py"
        test_file = ws_dir / "test_candidate.py"
        adapter_file = ws_dir / "adapter_patch.json"
        return impl_file, test_file, adapter_file

    # A) Test Real Execution - First run creates workspace stubs
    report_run1 = advance_capability_proposals(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    
    # Stubs are generated by default, so it must be downgraded to implementation_incomplete!
    assert report_run1["ready_for_human_review"] == 0
    res_prop1 = report_run1["per_proposal_results"]["capability_prop1"]
    assert res_prop1["status"] == "implementation_incomplete"
    assert "implementation_stub" in res_prop1["failed_gate"]
    assert "test_no_assertion" in res_prop1["failed_gate"]

    # B) Test compilable stub with NotImplementedError
    impl_file, test_file, adapter_file = get_workspace_files()
    impl_file.write_text("def cap1(*args, **kwargs):\n    raise NotImplementedError('draft stub')\n", encoding="utf-8")
    test_file.write_text("def test_cap1():\n    assert True\n", encoding="utf-8") # has assert, but implementation has NotImplementedError
    
    report_run2 = advance_capability_proposals(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert report_run2["per_proposal_results"]["capability_prop1"]["status"] == "implementation_incomplete"
    assert "implementation_stub" in report_run2["per_proposal_results"]["capability_prop1"]["failed_gate"]

    # C) Test empty test file with no assertion
    impl_file, test_file, adapter_file = get_workspace_files()
    impl_file.write_text("def cap1(*args, **kwargs):\n    return {'question_text': 'q', 'answer': 'a', 'semantic_answer': {}, 'answer_type': 'short_answer', 'presentation_mode': 'integer'}\n", encoding="utf-8")
    test_file.write_text("def test_cap1():\n    pass\n", encoding="utf-8") # no assertion
    
    report_run3 = advance_capability_proposals(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert report_run3["per_proposal_results"]["capability_prop1"]["status"] == "implementation_incomplete"
    assert "test_no_assertion" in report_run3["per_proposal_results"]["capability_prop1"]["failed_gate"]

    # D) Test adapter missing routing invocation
    impl_file, test_file, adapter_file = get_workspace_files()
    test_file.write_text("def test_cap1():\n    assert 1 == 1\n", encoding="utf-8")
    adapter_file.write_text(json.dumps({"route": "if op == 'other_op': convert()"}, indent=2), encoding="utf-8") # does not contain 'cap1'
    
    report_run4 = advance_capability_proposals(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert report_run4["per_proposal_results"]["capability_prop1"]["status"] == "implementation_incomplete"
    assert "adapter_no_invocation" in report_run4["per_proposal_results"]["capability_prop1"]["failed_gate"]

    # E) Fully working workspace passes and gets ready_for_human_review
    impl_file, test_file, adapter_file = get_workspace_files()
    adapter_file.write_text(json.dumps({"route": "if op == 'cap1': convert()"}, indent=2), encoding="utf-8")
    
    report_run5 = advance_capability_proposals(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert report_run5["ready_for_human_review"] == 1
    assert report_run5["per_proposal_results"]["capability_prop1"]["status"] == "ready_for_human_review"

def test_build_executable_domain_workspaces_scenarios(setup_env: tuple[Path, Path, sqlite3.Connection]):
    proposal_root, draft_root, conn = setup_env

    # 1. Setup Proposal (Valid implementation_incomplete proposal)
    p1 = {
        "proposal_schema": "domain_capability_proposal.v1",
        "proposal_id": "capability_prop2",
        "skill_id": "test_skill",
        "required_capabilities": ["collinear_trisection_coordinate"],
        "source_example_ids": [4426],
        "best_reuse_domain": "coordinate_geometry.division_point_coordinates",
        "recommended_action": "new_generic_operation",
        "status": "implementation_incomplete"
    }
    (proposal_root / "capability_prop2.json").write_text(json.dumps(p1), encoding="utf-8")

    # A) Test dry run - zero side effects, no files written
    dry_run_report = build_executable_domain_workspaces(
        skill_id="test_skill",
        dry_run=True,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert dry_run_report["total_incomplete"] == 1
    assert dry_run_report["implementations_created"] == 1
    assert dry_run_report["ready_for_human_review"] == 1
    
    # Check no files written in drafts root yet
    draft_files = list(draft_root.glob("**/*"))
    assert len(draft_files) == 0

    # B) Test Real execution - builds executable files and validates to ready_for_human_review
    real_report = build_executable_domain_workspaces(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert real_report["total_incomplete"] == 1
    assert real_report["implementations_created"] == 1
    assert real_report["ready_for_human_review"] == 1
    assert real_report["per_proposal_results"]["capability_prop2"]["status"] == "ready_for_human_review"

    # C) Verify files written on disk in workspace
    ws_dir = draft_root / "capability_prop2" / "revision_0001" / "workspace"
    impl_file = ws_dir / "implementation_candidate.py"
    test_file = ws_dir / "test_candidate.py"
    adapter_file = ws_dir / "adapter_patch.json"

    assert impl_file.is_file()
    assert test_file.is_file()
    assert adapter_file.is_file()

    impl_code = impl_file.read_text(encoding="utf-8")
    assert "def collinear_trisection_coordinate" in impl_code
    assert "NotImplementedError" not in impl_code

    test_code = test_file.read_text(encoding="utf-8")
    assert "assert check_answer" in test_code

    # D) Test idempotency - reset proposal to implementation_incomplete, rerun, impl is reused not rebuilt
    # After B) the proposal is marked ready_for_human_review on disk; reset it so the builder sees it again.
    import json as _json
    p_file = proposal_root / "capability_prop2.json"
    p_data = _json.loads(p_file.read_text(encoding="utf-8"))
    p_data["status"] = "implementation_incomplete"
    p_file.write_text(_json.dumps(p_data, ensure_ascii=False, indent=2), encoding="utf-8")

    re_report = build_executable_domain_workspaces(
        skill_id="test_skill",
        dry_run=False,
        proposal_root=proposal_root,
        draft_root=draft_root,
        db_conn=conn
    )
    assert re_report["implementations_reused"] == 1, f"Expected 1 reused, got: {re_report}"
    assert re_report["implementations_created"] == 0
    assert re_report["ready_for_human_review"] == 1
